import { FEE_PERCENT } from "@tradejs/core/constants";
import {
  BacktestPriceMode,
  Direction,
  Interval,
  StrategyConfig,
} from "@tradejs/types";

export interface LiquidityTailsSideConfig {
  enable: boolean;
  direction: Direction;
  minRiskRatio: number;
}

export const config = {
  ENV: "BACKTEST",
  INTERVAL: "15" as Interval,
  MAKE_ORDERS: true,
  CLOSE_OPPOSITE_POSITIONS: false,
  BACKTEST_PRICE_MODE: "open" as const,
  AI_ENABLED: false,
  AI_MODE: "llm" as const,
  ML_ENABLED: false,
  ML_THRESHOLD: 0.1,
  MIN_AI_QUALITY: 3,
  FEE_PERCENT,
  MAX_LOSS_VALUE: 10,
  MA_FAST: 14,
  MA_MEDIUM: 49,
  MA_SLOW: 50,
  OBV_SMA: 10,
  ATR: 14,
  ATR_PCT_SHORT: 7,
  ATR_PCT_LONG: 30,
  BB: 20,
  BB_STD: 2,
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,
  LIQUIDITY_TAILS_ATR_LENGTH: 14,
  LIQUIDITY_TAILS_ATR_MULT: 0.8,
  LIQUIDITY_TAILS_MIN_WICK_RATIO: 1.3,
  LIQUIDITY_TAILS_MIN_WICK_RATIO_LONG: 3,
  LIQUIDITY_TAILS_MIN_WICK_RATIO_SHORT: 3,
  LIQUIDITY_TAILS_WICK_DOMINANCE: 1.2,
  LIQUIDITY_TAILS_WICK_DOMINANCE_LONG: 2.2,
  LIQUIDITY_TAILS_WICK_DOMINANCE_SHORT: 3.5,
  LIQUIDITY_TAILS_MIN_GAP: 5,
  LIQUIDITY_TAILS_MAX_AGE: 500,
  LIQUIDITY_TAILS_KEEP_BROKEN: true,
  LIQUIDITY_TAILS_REACTION_CLOSE_BEYOND_ZONE: true,
  LIQUIDITY_TAILS_REQUIRE_REACTION_BODY: true,
  LIQUIDITY_TAILS_MAX_RETEST_DISTANCE_PCT: 1.2,
  LIQUIDITY_TAILS_MAX_RETEST_DISTANCE_PCT_LONG: 0.45,
  LIQUIDITY_TAILS_MAX_RETEST_DISTANCE_PCT_SHORT: 0.2,
  LIQUIDITY_TAILS_MIN_RETEST_AGE_BARS: 1,
  LIQUIDITY_TAILS_MIN_RETEST_AGE_BARS_LONG: undefined as number | undefined,
  LIQUIDITY_TAILS_MIN_RETEST_AGE_BARS_SHORT: undefined as number | undefined,
  LIQUIDITY_TAILS_MIN_ZONE_TOUCHES: 1,
  LIQUIDITY_TAILS_MIN_ZONE_TOUCHES_LONG: undefined as number | undefined,
  LIQUIDITY_TAILS_MIN_ZONE_TOUCHES_SHORT: undefined as number | undefined,
  LIQUIDITY_TAILS_MAX_ENTRY_RETEST_ORDINAL: 1,
  LIQUIDITY_TAILS_MAX_ENTRY_RETEST_ORDINAL_LONG: undefined as
    number | undefined,
  LIQUIDITY_TAILS_MAX_ENTRY_RETEST_ORDINAL_SHORT: undefined as
    number | undefined,
  LIQUIDITY_TAILS_MAX_ENTRY_ZONE_AGE_BARS: 0,
  LIQUIDITY_TAILS_MAX_ENTRY_ZONE_AGE_BARS_LONG: undefined as number | undefined,
  LIQUIDITY_TAILS_MAX_ENTRY_ZONE_AGE_BARS_SHORT: undefined as
    number | undefined,
  LIQUIDITY_TAILS_MIN_REJECTION_EFFICIENCY_RATIO: 6,
  LIQUIDITY_TAILS_MIN_REJECTION_EFFICIENCY_RATIO_LONG: undefined as
    number | undefined,
  LIQUIDITY_TAILS_MIN_REJECTION_EFFICIENCY_RATIO_SHORT: undefined as
    number | undefined,
  LIQUIDITY_TAILS_MIN_ORIGIN_VOLUME_REL20: 0,
  LIQUIDITY_TAILS_REQUIRE_ORIGIN_BODY_ALIGNED: false,
  LIQUIDITY_TAILS_REQUIRE_ORIGIN_BODY_ALIGNED_SHORT_ONLY: false,
  LIQUIDITY_TAILS_MIN_RETEST_PENETRATION_PCT: 0,
  LIQUIDITY_TAILS_MIN_REACTION_DISTANCE_ATR: 0,
  LIQUIDITY_TAILS_CLOSE_HOLD_BARS: 0,
  LIQUIDITY_TAILS_CLOSE_HOLD_BARS_LONG: undefined as number | undefined,
  LIQUIDITY_TAILS_CLOSE_HOLD_BARS_SHORT: undefined as number | undefined,
  LIQUIDITY_TAILS_STOP_ATR_BUFFER_MULT: 0.12,
  LIQUIDITY_TAILS_STOP_BUFFER_PCT: 0.03,
  LIQUIDITY_TAILS_TARGET_R_MULT: 1.15,
  LIQUIDITY_TAILS_TARGET_R_MULT_LONG: undefined as number | undefined,
  LIQUIDITY_TAILS_TARGET_R_MULT_SHORT: undefined as number | undefined,
  LIQUIDITY_TAILS_EXIT_ON_OPPOSITE_RETEST: false,
  LIQUIDITY_TAILS_EXIT_ON_INVALIDATION: false,
  LIQUIDITY_TAILS_EXIT_ON_INVALIDATION_LONG: undefined as boolean | undefined,
  LIQUIDITY_TAILS_EXIT_ON_INVALIDATION_SHORT: undefined as boolean | undefined,
  LIQUIDITY_TAILS_EXIT_ON_SCALE_IN_RETEST: false,
  LIQUIDITY_TAILS_SCALE_IN_ENABLED: true,
  LIQUIDITY_TAILS_SCALE_IN_COUNT: 1,
  LIQUIDITY_TAILS_INITIAL_RISK_FRACTION: 0.7,
  LIQUIDITY_TAILS_SCALE_IN_MIN_IMPROVEMENT_ATR: 1,
  LIQUIDITY_TAILS_MAX_FIGURE_ZONES: 24,
  LONG: {
    enable: true,
    direction: "LONG",
    minRiskRatio: 1,
  },
  SHORT: {
    enable: true,
    direction: "SHORT",
    minRiskRatio: 1,
  },
} as const;

export type LiquidityTailsConfig = StrategyConfig &
  Omit<
    typeof config,
    | "BACKTEST_PRICE_MODE"
    | "LIQUIDITY_TAILS_EXIT_ON_INVALIDATION"
    | "LIQUIDITY_TAILS_EXIT_ON_OPPOSITE_RETEST"
    | "LIQUIDITY_TAILS_EXIT_ON_SCALE_IN_RETEST"
    | "LIQUIDITY_TAILS_INITIAL_RISK_FRACTION"
    | "LIQUIDITY_TAILS_SCALE_IN_COUNT"
    | "LIQUIDITY_TAILS_SCALE_IN_MIN_IMPROVEMENT_ATR"
    | "LIQUIDITY_TAILS_SCALE_IN_ENABLED"
    | "LONG"
    | "SHORT"
  > & {
    BACKTEST_PRICE_MODE: BacktestPriceMode;
    LIQUIDITY_TAILS_EXIT_ON_INVALIDATION: boolean;
    LIQUIDITY_TAILS_EXIT_ON_OPPOSITE_RETEST: boolean;
    LIQUIDITY_TAILS_EXIT_ON_SCALE_IN_RETEST: boolean;
    LIQUIDITY_TAILS_INITIAL_RISK_FRACTION: number;
    LIQUIDITY_TAILS_SCALE_IN_COUNT: number;
    LIQUIDITY_TAILS_SCALE_IN_MIN_IMPROVEMENT_ATR: number;
    LIQUIDITY_TAILS_SCALE_IN_ENABLED: boolean;
    LONG: LiquidityTailsSideConfig;
    SHORT: LiquidityTailsSideConfig;
  };
